version: '3.7'
services:
  mongo_crypto:
    image: mongo:4
    ports:
      - 27017:27017

  rabbitmq:
      image: rabbitmq:3.7.5
      hostname: rabbitmq
      ports:
        - 5672:5672
      expose:
        - 5672
      environment:
        RABBITMQ_DEFAULT_USER: 'user'
        RABBITMQ_DEFAULT_PASS: 'password'
        RABBITMQ_DEFAULT_VHOST: 'my_vhost'